#pragma once

#define LIBOSMO_NETIF_VERSION {{VERSION}}
#define LIBOSMO_NETIF_VERSION_STR "{{VERSION}}"

#define LIBOSMO_NETIF_VERSION_MAJOR {{VERSION_MAJOR}}
#define LIBOSMO_NETIF_VERSION_MINOR {{VERSION_MINOR}}
#define LIBOSMO_NETIF_VERSION_PATCH {{VERSION_PATCH}}

#define LIBOSMO_NETIF_VERSION_GREATER_EQUAL(major, minor, patch) \
	(LIBOSMO_NETIF_VERSION_MAJOR > (major) || \
	 (LIBOSMO_NETIF_VERSION_MAJOR == (major) && \
	  LIBOSMO_NETIF_VERSION_MINOR > (minor)) || \
	 (LIBOSMO_NETIF_VERSION_MAJOR == (major) && \
	  LIBOSMO_NETIF_VERSION_MINOR == (minor) && \
	  LIBOSMO_NETIF_VERSION_PATCH >= (patch)))
